USE [master]
GO

/****** Object:  Database [CentralUniversityDB]    Script Date: 11-Jul-18 2:52:43 PM ******/
CREATE DATABASE [CentralUniversityDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CentralUniversityDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\CentralUniversityDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CentralUniversityDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\CentralUniversityDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CentralUniversityDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CentralUniversityDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CentralUniversityDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CentralUniversityDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CentralUniversityDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CentralUniversityDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CentralUniversityDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET RECOVERY FULL 
GO

ALTER DATABASE [CentralUniversityDB] SET  MULTI_USER 
GO

ALTER DATABASE [CentralUniversityDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CentralUniversityDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CentralUniversityDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CentralUniversityDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CentralUniversityDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CentralUniversityDB] SET  READ_WRITE 
GO

